### ISSUE TITLE
Issue with Makefile: PythonInstall section not present

### ISSUE THREAD

**Issue by varun-go** [JingHuangLab/openmm_deepmd_plugin#26]
I recently rebuilt this plugin for a new conda environment I created. I noticed that after running `make install`, the `make test` command only outputs 2 tests: 

```
make test
Running tests...
Test project /home/sarupria/gopal145/software/openmm_deepmd_plugin_v4/build
    Start 1: TestSerializeDeepmdForce
1/2 Test #1: TestSerializeDeepmdForce .........Subprocess aborted***Exception:   8.06 sec
    Start 2: TestDeepmdPlugin4Reference
2/2 Test #2: TestDeepmdPlugin4Reference .......Subprocess aborted***Exception:   0.78 sec
```
However, I recall that a previous version of the code generated 4 tests where the final two tests were in regards to using CUDA. I also get an error when running `make PythonInstall` which states that there is no rule to make target `PythonInstall`.
```
make PythonInstall
make: *** No rule to make target 'PythonInstall'.  Stop.
```
I have confirmed that this section is not present in the Makefile. Additionally, this section is present in a previous version of the Makefile (created in Feb 2024). Both files are attached for reference. 

As a result of these issues, I am unable to build the plugin now. I noticed that there were two commits in March and I am not sure if those could have had an impact. 
[Makefile_old.txt](https://github.com/user-attachments/files/15795558/Makefile_old.txt)
[Makefile_new.txt](https://github.com/user-attachments/files/15795559/Makefile_new.txt)

**Comment by dingye18** [comment]
( Sorry for reply so late again......
Did you installed swig in your environment. 
Swig is installed like this:

```shell
conda install swig=4.0.1 -c conda-forge
```

It looks like I forgot to add the `swig` when installed from source. Sorry.
Btw, if the cuda environment was not detected, the two tests for cuda platform will not be showed too. 
That's the reason for two tests only in your report.

**Comment by varun-go** [comment]
Installing swig resolved the issue. The CUDA-specific tests are also showing now, and they all passed. Thank you!
